In [ ]:
#Reminders
add data to gitignore file

## Set up steps

#### Import relevant Python libraries

In [1]:
#import libaries
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

#### Import heart data into a dataframe

In [2]:
heart_data = pd.read_csv("data/heart.csv")

## Examine the Data

#### Preview the data and get basic information

In [3]:
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
heart_data.info()
#this dataset has 33 rows and 14 columns, most values are integer data types and the remaining is float values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


#### Search for missing values

In [14]:
missing_values_count = heart_data.isnull().sum()
missing_values_count
#There are no missing values in any of the columns

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

#### Search for inconsistency in the way the data is entered and view the distribution

In [12]:
#Is the data within each column entered consistently?  
#And, how is the data in each column distributed? (plot the data)

age = heart_data['age'].unique()
age


array([1, 0], dtype=int64)

In [ ]:
#AGE PLOT GOES HERE

In [15]:
gender = heart_data['sex'].unique()
gender

array([1, 0], dtype=int64)

In [ ]:
# GENDER PLOT GOES HERE

In [16]:
chest_pain_type = heart_data['cp'].unique()
chest_pain_type

array([3, 2, 1, 0], dtype=int64)

In [ ]:
# CHEST PAIN TYPE PLOT GOES HERE

In [17]:
resting_blood_pressure = heart_data['trestbps'].unique()
resting_blood_pressure

array([145, 130, 120, 140, 172, 150, 110, 135, 160, 105, 125, 142, 155,
       104, 138, 128, 108, 134, 122, 115, 118, 100, 124,  94, 112, 102,
       152, 101, 132, 148, 178, 129, 180, 136, 126, 106, 156, 170, 146,
       117, 200, 165, 174, 192, 144, 123, 154, 114, 164], dtype=int64)

In [ ]:
# RESTING BLOOD PRESSURE PLOT GOES HERE

Key questions to answer
1. How many data points do I have? Enough for ML? Enough of the classes I’m trying to predict?
2. What are the columns? Column ranges?
3 What will my normalization strategy be? Do I have outliers? Are things in ranges that I expect?
4. What are the datatypes, and will they behave like I expect?
5. Are any numbers stored as strings? Will I have to clean them to get them to be numbers?
6. Do I have any missing values?  Any duplications? How many? Why?
7. Are features correlated?
8. In expected, gut-check ways, in novel ways, but also in data leakage ways: Do I have any weird distributions?
   (Huge skews, bimodal, uniform…)

In [ ]:
#Do any of the columns include similar data - but scaled quite differently? (ex: ft vs. mile for length)